alias: 302_EV_Charging_CurrentChanged
description: |
  # EV Charging Monitor - Current Changes
  Version: 1.7.0
  Last Updated: 2025-03-02
  
  ## Functions:
  1. Monitors charging current adjustments
  2. Validates charging parameters
  3. Tracks real-time charging estimates
  4. Provides updated charging metrics
triggers:
  - platform: state
    entity_id: number.eveus_ev_charger_charging_current
    id: current_trigger
conditions:
  - condition: state
    entity_id: sensor.eveus_ev_charger_state
    state: Charging
  - condition: template
    value_template: >
      {% set current = states('number.eveus_ev_charger_charging_current')|float(0) %}
      {% set prev = trigger.from_state.state|float(0) if trigger.from_state is not none else 0 %}
      {{ current != prev and current >= 6 }}
  - condition: numeric_state
    entity_id: sensor.eveus_ev_charger_power
    above: 100
actions:
  - data:
      title: "*EV* ðŸ”Œ *Current Changed* | {{ current_amps|round(0)|int }}A"
      message: |
        â° ETA: {{ time_data.eta }} (in {{ time_data.duration }})
        ðŸ”‹ SoC: {{ soc_data.current|round(0) }}% â†’ {{ soc_data.target|round(0)
        }}% (+{{ soc_data.increase|round(0) }}%)
        âš¡ Energy: {{ soc_data.current_kwh }}kWh â†’ {{ soc_data.target_kwh }}kWh
        (+{{ soc_data.added_kwh }}kWh)
    action: notify.harold
variables:
  current_amps: "{{ states('number.eveus_ev_charger_charging_current')|float(0) }}"
  soc_data:
    current: "{{ states('sensor.eveus_ev_charger_soc_percent')|float(0) }}"
    target: "{{ states('input_number.ev_target_soc')|float(80) }}"
    increase: >
      {{ states('input_number.ev_target_soc')|float(80) -
      states('sensor.eveus_ev_charger_soc_percent')|float(0) }}
    capacity: "{{ states('input_number.ev_battery_capacity')|float(80) }}"
    current_kwh: >
      {{ (states('input_number.ev_battery_capacity')|float(80) *
      states('sensor.eveus_ev_charger_soc_percent')|float(0) / 100)|round(1) }}
    target_kwh: >
      {{ (states('input_number.ev_battery_capacity')|float(80) *
      states('input_number.ev_target_soc')|float(80) / 100)|round(1) }}
    added_kwh: >
      {{ ((states('input_number.ev_battery_capacity')|float(80) *
      states('input_number.ev_target_soc')|float(80) / 100) - 
          (states('input_number.ev_battery_capacity')|float(80) * states('sensor.eveus_ev_charger_soc_percent')|float(0) / 100))|round(1) }}
  time_data:
    eta: >
      {% set correction = states('input_number.ev_soc_correction')|float(7.5) %}
      {% set remaining_kwh = ((states('input_number.ev_target_soc')|float(80) -
                             states('sensor.eveus_ev_charger_soc_percent')|float(0)) * 
                             states('input_number.ev_battery_capacity')|float(80) / 100) %}
      {% set adjusted_power = 230 * states('number.eveus_ev_charger_charging_current')|float(0) * 0.9 / 1000 %}
      {% set power_kw = adjusted_power * (1 - correction / 100) %}
      {% set power_kw = power_kw if power_kw > 0 else 1 %}
      {% set total_minutes = (remaining_kwh / power_kw * 60)|round(0) %}
      {% set completion = now() + timedelta(minutes=total_minutes) %}
      {{ completion.strftime('%H:%M %d.%m.%Y') }}
    duration: >
      {% set correction = states('input_number.ev_soc_correction')|float(7.5) %}
      {% set remaining_kwh = ((states('input_number.ev_target_soc')|float(80) -
                             states('sensor.eveus_ev_charger_soc_percent')|float(0)) * 
                             states('input_number.ev_battery_capacity')|float(80) / 100) %}
      {% set adjusted_power = 230 * states('number.eveus_ev_charger_charging_current')|float(0) * 0.9 / 1000 %}
      {% set power_kw = adjusted_power * (1 - correction / 100) %}
      {% set power_kw = power_kw if power_kw > 0 else 1 %}
      {% set total_minutes = (remaining_kwh / power_kw * 60)|round(0) %}
      {% set hours = (total_minutes / 60)|int %}
      {% set mins = (total_minutes % 60)|int %}
      {{ hours|string + 'h ' + ('%02d'|format(mins)) + 'm' }}
mode: restart
max_exceeded: silent
